/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacasino.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sistemacasino.datos.Casino;
import sistemacasino.datos.Usuario;

/**
 *
 * @author Steven
 */
public class FormEliminarMetodo extends javax.swing.JFrame {
    Usuario usuario;
    Casino casino;
    /**
     * Creates new form NewJFrame
     */
    public FormEliminarMetodo(Casino casino, Usuario usuario){
        this.casino=casino;
        this.usuario=usuario;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RadioTarjeta = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        ButtonCancelar = new javax.swing.JButton();
        ButtonHecho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione el metodo a eliminar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, -1));

        buttonGroup1.add(RadioTarjeta);
        RadioTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        RadioTarjeta.setText("Tarjeta");
        RadioTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(RadioTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Tansferencia Bancaria");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        ButtonHecho.setText("Hecho");
        ButtonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHechoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonHecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bolivia/game/res/metodo pago.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTarjetaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RadioTarjetaActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void ButtonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHechoActionPerformed
        // TODO add your handling code here:
       if(RadioTarjeta.isSelected()){
           if(casino.buscarUsuario(usuario.getCedula()).eliminarMetodo("Tarjeta")) JOptionPane.showMessageDialog(this, "Metodo eliminado con exito");
           else JOptionPane.showMessageDialog(null, "No paso nada");
       }else{
           if(casino.buscarUsuario(usuario.getCedula()).eliminarMetodo("Tranferencia Bancaria")) JOptionPane.showMessageDialog(this, "Metodo eliminado con exito");
           else JOptionPane.showMessageDialog(null, "No paso nada");
       }
       setVisible(false);
    }//GEN-LAST:event_ButtonHechoActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonHecho;
    private javax.swing.JRadioButton RadioTarjeta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
