/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacasino.gui;

import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sistemacasino.persistencia.Serializacion;
import sistemacasino.datos.Casino;
import sistemacasino.datos.MetodoPago;
import sistemacasino.datos.Tarjeta;
import sistemacasino.datos.TransferenciaBancaria;
import sistemacasino.datos.Usuario;
import sistemacasino.exceptions.DateException;

/**
 *
 * @author Steven
 */
public class FormMetodoPago extends javax.swing.JFrame {
    Usuario usuario;
    Casino casino;
    /**
     * Creates new form FormMetodoPago
     */
    public FormMetodoPago(Casino casino,Usuario usuario) {
        initComponents();
        this.casino=casino;
        this.usuario=usuario;
        jLabel3.setVisible(false);
        txtFechaVencimiento.setVisible(false);
        jLabel4.setVisible(false);
        txtCodigoSeguridad.setVisible(false);
        jLabel5.setVisible(false);
        combotipo.setVisible(false);
        ButtonHecho.setVisible(false);
        jLabel6.setVisible(false);
        txtCodigoSwift.setVisible(false);
        jLabel7.setVisible(false);
        txtCodigoIban.setVisible(false);
        jLabel8.setVisible(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RadioTarjeta = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtFechaVencimiento = new javax.swing.JTextField();
        txtCodigoIban = new javax.swing.JTextField();
        txtCodigoSeguridad = new javax.swing.JTextField();
        txtCodigoSwift = new javax.swing.JTextField();
        combotipo = new javax.swing.JComboBox<>();
        ButtonHecho = new javax.swing.JButton();
        ButtonCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione el metodo a agregar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, -1));

        buttonGroup1.add(RadioTarjeta);
        RadioTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        RadioTarjeta.setText("Tarjeta");
        RadioTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(RadioTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Tansferencia Bancaria");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));
        jPanel1.add(txtFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));
        jPanel1.add(txtCodigoIban, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 80, -1));
        jPanel1.add(txtCodigoSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 100, -1));
        jPanel1.add(txtCodigoSwift, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 80, -1));

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debito", "Credito" }));
        jPanel1.add(combotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        ButtonHecho.setText("Hecho");
        ButtonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHechoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonHecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("yyyy-mm-dd");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Codigo iban:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo swift:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Tarjeta: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Codigo seguridad: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha vencimiento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bolivia/game/res/metodo pago.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTarjetaActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        txtCodigoSwift.setVisible(false);
        jLabel7.setVisible(false);
        txtCodigoIban.setVisible(false);
        jLabel3.setVisible(true);
        txtFechaVencimiento.setVisible(true);
        jLabel4.setVisible(true);
        txtCodigoSeguridad.setVisible(true);
        jLabel5.setVisible(true);
        combotipo.setVisible(true);
        ButtonHecho.setVisible(true);
        jLabel8.setVisible(true);
    }//GEN-LAST:event_RadioTarjetaActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        txtFechaVencimiento.setVisible(false);
        jLabel4.setVisible(false);
        txtCodigoSeguridad.setVisible(false);
        jLabel5.setVisible(false);
        combotipo.setVisible(false);
        jLabel8.setVisible(false);
        jLabel6.setVisible(true);
        txtCodigoSwift.setVisible(true);
        jLabel7.setVisible(true);
        txtCodigoIban.setVisible(true);
        ButtonHecho.setVisible(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void ButtonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHechoActionPerformed
        // TODO add your handling code here:
        try{
            if(RadioTarjeta.isSelected()){
                LocalDate fecha = LocalDate.parse(txtFechaVencimiento.getText());
                if(fecha.isBefore(LocalDate.now())) throw new DateException("Fecha no valida.");
                int codigo = Integer.parseInt(txtCodigoSeguridad.getText());
                Tarjeta tarjeta = new Tarjeta(fecha, codigo,(String) combotipo.getSelectedItem(),"Tarjeta" );
                casino.buscarUsuario(usuario.getCedula()).agregarMetodo(tarjeta);
                new Serializacion().guardar(casino, "Casino.data");
            }else{
                int codigo1= Integer.parseInt(txtCodigoSwift.getText());
                int codigo2= Integer.parseInt(txtCodigoIban.getText());
                TransferenciaBancaria trans= new TransferenciaBancaria(codigo1, codigo2, "Transferencia Bancaria");
                casino.buscarUsuario(usuario.getCedula()).agregarMetodo(trans);
                new Serializacion().guardar(casino, "Casino.data");
            }
            setVisible(false);
            JOptionPane.showMessageDialog(this, "Metodo agregado con exito.");
        }catch(DateException | NumberFormatException | DateTimeParseException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_ButtonHechoActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_ButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonHecho;
    private javax.swing.JRadioButton RadioTarjeta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txtCodigoIban;
    private javax.swing.JTextField txtCodigoSeguridad;
    private javax.swing.JTextField txtCodigoSwift;
    private javax.swing.JTextField txtFechaVencimiento;
    // End of variables declaration//GEN-END:variables
}
