/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacasino.gui;

import java.io.IOException;
import sistemacasino.exceptions.NotFoundMetodoExcetion;
import sistemacasino.exceptions.CantidadException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sistemacasino.persistencia.Serializacion;
import sistemacasino.datos.Casino;
import sistemacasino.datos.Usuario;
import sistemacasino.exceptions.NegativeException;

/**
 *
 * @author Steven
 */
public class FormTransacción extends javax.swing.JFrame {
    Casino casino;
    Usuario usuario;
    /**
     * Creates new form FromRecarga
     * @param casino
     * @param usuario
     */
    public FormTransacción(Casino casino, Usuario usuario) {
        initComponents();
        this.casino=casino;
        this.usuario=usuario;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonHecho = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        comboMetodo = new javax.swing.JComboBox<>();
        RadioRecarga = new javax.swing.JRadioButton();
        RadioRetiro = new javax.swing.JRadioButton();
        ButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Metodo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        ButtonHecho.setText("Hecho");
        ButtonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHechoActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonHecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        comboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Transferencia Bancaria" }));
        jPanel1.add(comboMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        buttonGroup1.add(RadioRecarga);
        RadioRecarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RadioRecarga.setForeground(new java.awt.Color(255, 255, 255));
        RadioRecarga.setText("Recarga");
        RadioRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRecargaActionPerformed(evt);
            }
        });
        jPanel1.add(RadioRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        buttonGroup1.add(RadioRetiro);
        RadioRetiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RadioRetiro.setForeground(new java.awt.Color(255, 255, 255));
        RadioRetiro.setText("Retiro");
        RadioRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioRetiroActionPerformed(evt);
            }
        });
        jPanel1.add(RadioRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 30));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bolivia/game/res/retiro.jpeg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void RadioRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioRecargaActionPerformed

    private void RadioRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioRetiroActionPerformed

    private void ButtonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHechoActionPerformed
        // TODO add your handling code here:
        try{
            float cantidad = Float.parseFloat(txtCantidad.getText());
            if(usuario.buscarMetodo((String) comboMetodo.getSelectedItem())==null) throw new NotFoundMetodoExcetion("No cuenta con ese metodo de pago.");
            String tipo;
            if(RadioRecarga.isSelected()){
                tipo="Recarga";
                casino.buscarUsuario(usuario.getCedula()).getBilletera().consignar(cantidad);
            }else{
                tipo="Retiro";
                if(cantidad>usuario.getBilletera().getSaldo()) throw new CantidadException("Saldo insuficiente.");
                casino.buscarUsuario(usuario.getCedula()).getBilletera().retirar(cantidad);
            }
            casino.agregarTransaccion(usuario.getCedula(), (String) comboMetodo.getSelectedItem(),tipo, cantidad);
            new Serializacion().guardar(casino, "Casino.data");
            setVisible(false);
        }catch(NumberFormatException | NegativeException ex){
            JOptionPane.showMessageDialog(this, "Ingrese una cantidad valida");
        } catch (CantidadException | NotFoundMetodoExcetion | IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_ButtonHechoActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_ButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonHecho;
    private javax.swing.JRadioButton RadioRecarga;
    private javax.swing.JRadioButton RadioRetiro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
