/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemacasino.gui;

import java.io.IOException;
import javax.swing.JOptionPane;
import org.bolivia.game.DinoBettingGame;
import org.bolivia.game.RuletaPanel;
import org.bolivia.game.TragaMonedas;
import sistemacasino.persistencia.Serializacion;
import sistemacasino.datos.Casino;
import sistemacasino.datos.Usuario;

/**
 *
 * @author Steven
 */
public class Menu extends javax.swing.JFrame {
    Usuario usuario;
    Casino casino;
    /**
     * Creates new form MenuCliente
     * @param cedula
     * @param casino
     */
    public Menu(int cedula, Casino casino) {
        initComponents();
        this.casino=casino;
        usuario=casino.buscarUsuario(cedula);
        txtNombreUsuario.setText(usuario.getNombre());
        if(usuario.getTipo().equals("Moderador")){
            MenuJuegos.setVisible(false);
        }
        if(usuario.getTipo().equals("Soporte")){
            MenuGestionar.setVisible(false);
        }
        if(usuario.getTipo().equals("Cliente")){
            MenuGestionar.setVisible(false);
            ButtonComentaiosJuego.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ButtonRuleta = new javax.swing.JButton();
        ButtonDino = new javax.swing.JButton();
        ButtonTraga = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MenuPerfil = new javax.swing.JMenu();
        ButtonEditarPerfil = new javax.swing.JMenuItem();
        MenuCartera = new javax.swing.JMenu();
        ButtonTransacción = new javax.swing.JMenuItem();
        ButtonAggMetodo = new javax.swing.JMenuItem();
        ButtonQuiMetodo = new javax.swing.JMenuItem();
        ButtonVerMetodos = new javax.swing.JMenuItem();
        ButtonVerCartera = new javax.swing.JMenuItem();
        MenuGestionar = new javax.swing.JMenu();
        MenuUsuarios = new javax.swing.JMenu();
        ButtonEditarUsuario = new javax.swing.JMenuItem();
        ButtonBorrarUsuario = new javax.swing.JMenuItem();
        ButtonListarUsuarios = new javax.swing.JMenuItem();
        ButtonVerTransacciones = new javax.swing.JMenuItem();
        MenuJuegos = new javax.swing.JMenu();
        ButtonEditarJuego = new javax.swing.JMenuItem();
        ButtonBorrarJuego = new javax.swing.JMenuItem();
        ButtonAgregarPremioJuego = new javax.swing.JMenuItem();
        ButtonEliminarPremioJuego = new javax.swing.JMenuItem();
        ButtonListarJuegos = new javax.swing.JMenuItem();
        ButtonPremiosJuego = new javax.swing.JMenuItem();
        MenuSoporte = new javax.swing.JMenu();
        ButtonEnviarComentario = new javax.swing.JMenuItem();
        ButtonComentaiosJuego = new javax.swing.JMenuItem();
        ButtonListarComentariosEnviados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 20));

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setRequestFocusEnabled(false);
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 130, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));

        ButtonRuleta.setText("Jugar");
        ButtonRuleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRuletaActionPerformed(evt);
            }
        });

        ButtonDino.setText("Jugar");
        ButtonDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDinoActionPerformed(evt);
            }
        });

        ButtonTraga.setText("Jugar");
        ButtonTraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTragaActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Traga Monedas");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ruleta de la suerte");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DinoBetting");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("1.");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("2.");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("3.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(ButtonTraga)
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonRuleta)
                                .addGap(17, 17, 17)))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonDino)
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRuleta)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDino)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTraga)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bolivia/game/res/casino1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        MenuPerfil.setText("Perfil");

        ButtonEditarPerfil.setText("Editar perfil");
        ButtonEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarPerfilActionPerformed(evt);
            }
        });
        MenuPerfil.add(ButtonEditarPerfil);

        MenuBar.add(MenuPerfil);

        MenuCartera.setText("Cartera");

        ButtonTransacción.setText("Transacción");
        ButtonTransacción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransacciónActionPerformed(evt);
            }
        });
        MenuCartera.add(ButtonTransacción);

        ButtonAggMetodo.setText("Agregar metodo pago");
        ButtonAggMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAggMetodoActionPerformed(evt);
            }
        });
        MenuCartera.add(ButtonAggMetodo);

        ButtonQuiMetodo.setText("Quitar metodo pago");
        ButtonQuiMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonQuiMetodoActionPerformed(evt);
            }
        });
        MenuCartera.add(ButtonQuiMetodo);

        ButtonVerMetodos.setText("Listar metodos");
        ButtonVerMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerMetodosActionPerformed(evt);
            }
        });
        MenuCartera.add(ButtonVerMetodos);

        ButtonVerCartera.setText("Ver Cartera");
        ButtonVerCartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerCarteraActionPerformed(evt);
            }
        });
        MenuCartera.add(ButtonVerCartera);

        MenuBar.add(MenuCartera);

        MenuGestionar.setText("Gestionar");

        MenuUsuarios.setText("Usuarios");

        ButtonEditarUsuario.setText("Editar usuario");
        ButtonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarUsuarioActionPerformed(evt);
            }
        });
        MenuUsuarios.add(ButtonEditarUsuario);

        ButtonBorrarUsuario.setText("Borrar usuario");
        ButtonBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarUsuarioActionPerformed(evt);
            }
        });
        MenuUsuarios.add(ButtonBorrarUsuario);

        ButtonListarUsuarios.setText("Listar usuarios");
        ButtonListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarUsuariosActionPerformed(evt);
            }
        });
        MenuUsuarios.add(ButtonListarUsuarios);

        ButtonVerTransacciones.setText("Listar Transacciones usuario");
        ButtonVerTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVerTransaccionesActionPerformed(evt);
            }
        });
        MenuUsuarios.add(ButtonVerTransacciones);

        MenuGestionar.add(MenuUsuarios);

        MenuJuegos.setText("Juegos");

        ButtonEditarJuego.setText("Editar juego");
        ButtonEditarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarJuegoActionPerformed(evt);
            }
        });
        MenuJuegos.add(ButtonEditarJuego);

        ButtonBorrarJuego.setText("Borrar juego");
        ButtonBorrarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarJuegoActionPerformed(evt);
            }
        });
        MenuJuegos.add(ButtonBorrarJuego);

        ButtonAgregarPremioJuego.setText("Agregar premio juego");
        ButtonAgregarPremioJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarPremioJuegoActionPerformed(evt);
            }
        });
        MenuJuegos.add(ButtonAgregarPremioJuego);

        ButtonEliminarPremioJuego.setText("Eliminar premio juego");
        ButtonEliminarPremioJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarPremioJuegoActionPerformed(evt);
            }
        });
        MenuJuegos.add(ButtonEliminarPremioJuego);

        ButtonListarJuegos.setText("Listar Juegos");
        ButtonListarJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarJuegosActionPerformed(evt);
            }
        });
        MenuJuegos.add(ButtonListarJuegos);

        ButtonPremiosJuego.setText("Listar premios juego");
        ButtonPremiosJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPremiosJuegoActionPerformed(evt);
            }
        });
        MenuJuegos.add(ButtonPremiosJuego);

        MenuGestionar.add(MenuJuegos);

        MenuBar.add(MenuGestionar);

        MenuSoporte.setText("Soporte al cliente");

        ButtonEnviarComentario.setText("Enviar un comentario");
        ButtonEnviarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarComentarioActionPerformed(evt);
            }
        });
        MenuSoporte.add(ButtonEnviarComentario);

        ButtonComentaiosJuego.setText("Ver comentarios juego");
        ButtonComentaiosJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonComentaiosJuegoActionPerformed(evt);
            }
        });
        MenuSoporte.add(ButtonComentaiosJuego);

        ButtonListarComentariosEnviados.setText("Listar comentarios enviados");
        ButtonListarComentariosEnviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarComentariosEnviadosActionPerformed(evt);
            }
        });
        MenuSoporte.add(ButtonListarComentariosEnviados);

        MenuBar.add(MenuSoporte);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void ButtonEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarPerfilActionPerformed
        // TODO add your handling code here:
        new FormEditarUsuario(casino, usuario).setVisible(true);
    }//GEN-LAST:event_ButtonEditarPerfilActionPerformed

    private void ButtonTransacciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransacciónActionPerformed
        // TODO add your handling code here:
        if(usuario.buscarMetodo("Tarjeta")!=null || usuario.buscarMetodo("Transferencia Bancaria")!=null){
            new FormTransacción(casino, usuario).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No cuenta con ningun metodo de pago, agregue alguno.");
        }
    }//GEN-LAST:event_ButtonTransacciónActionPerformed

    private void ButtonListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarUsuariosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, casino.listarUsuarios());
    }//GEN-LAST:event_ButtonListarUsuariosActionPerformed

    private void ButtonQuiMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonQuiMetodoActionPerformed
        // TODO add your handling code here:
        if(usuario.buscarMetodo("Tarjeta")!=null || usuario.buscarMetodo("Transferencia Bancaria")!=null){
            new FormEliminarMetodo(casino, usuario).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No cuenta con ningun metodo de pago, agregue alguno.");
        }
    }//GEN-LAST:event_ButtonQuiMetodoActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonAggMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAggMetodoActionPerformed
        // TODO add your handling code here:
        new FormMetodoPago(casino, usuario).setVisible(true);
    }//GEN-LAST:event_ButtonAggMetodoActionPerformed

    private void ButtonVerMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerMetodosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, casino.listarMetodosUsuario(usuario.getCedula()));
    }//GEN-LAST:event_ButtonVerMetodosActionPerformed

    private void ButtonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarUsuarioActionPerformed
        // TODO add your handling code here:
        try{
            int cedula = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cedula del usuario a editar:"));
            new FormEditarUsuario(casino, casino.buscarUsuario(cedula)).setVisible(true);
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese una cedula valida!");
        }
    }//GEN-LAST:event_ButtonEditarUsuarioActionPerformed

    private void ButtonVerCarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerCarteraActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, usuario.getBilletera().toString());
    }//GEN-LAST:event_ButtonVerCarteraActionPerformed

    private void ButtonBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarUsuarioActionPerformed
        // TODO add your handling code here:
        try{
            int cedula = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cedula del usuario a borrar:"));
            if(casino.eliminarUsuario(cedula)) JOptionPane.showMessageDialog(this, "Se ha borrado con exito");
            else JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            new Serializacion().guardar(casino, "Casino.data");
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese una cedula valida!");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_ButtonBorrarUsuarioActionPerformed

    private void ButtonVerTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVerTransaccionesActionPerformed
        // TODO add your handling code here:
        try{
            int cedula = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cedula del usuario:"));
            JOptionPane.showMessageDialog(this, casino.listarTransaccionesUsuario(cedula));
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese una cedula valida!");
        }
    }//GEN-LAST:event_ButtonVerTransaccionesActionPerformed

    private void ButtonDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDinoActionPerformed
        // TODO add your handling code here:
        new TragaMonedas("Traga monedas", "",usuario,casino).setVisible(true);
    }//GEN-LAST:event_ButtonDinoActionPerformed

    private void ButtonEditarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarJuegoActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del juego:"));
            new FormJuego(casino, id).setVisible(true);
        } catch(NumberFormatException ex){
            
        }
    }//GEN-LAST:event_ButtonEditarJuegoActionPerformed

    private void ButtonBorrarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarJuegoActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del juego:"));
            if(casino.getArcade().eliminarJuego(id)) JOptionPane.showMessageDialog(this, "Juego editado con exito!");
            else JOptionPane.showConfirmDialog(this, "No se encontro el juego");
        } catch(NumberFormatException ex){  
        }
    }//GEN-LAST:event_ButtonBorrarJuegoActionPerformed

    private void ButtonAgregarPremioJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarPremioJuegoActionPerformed
        // TODO add your handling code here:
        try{
            int id= Integer.parseInt(JOptionPane.showInputDialog("Ingres el id del juego:"));
            new FormPremio(casino, id).setVisible(true);
        }catch(NumberFormatException ex){
        }
    }//GEN-LAST:event_ButtonAgregarPremioJuegoActionPerformed

    private void ButtonEliminarPremioJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarPremioJuegoActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del juego:"));
            String premio = JOptionPane.showInputDialog("Ingrese el nombre del premio: ");
            if(casino.getArcade().buscarJuego(id).eliminarPremio(premio)) JOptionPane.showMessageDialog(this, "Premio borrado!");
            else JOptionPane.showConfirmDialog(this, "No se encontro el juego");
        } catch(NumberFormatException ex){  
        }
    }//GEN-LAST:event_ButtonEliminarPremioJuegoActionPerformed

    private void ButtonListarJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarJuegosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, casino.getArcade().listarJuegos());
    }//GEN-LAST:event_ButtonListarJuegosActionPerformed

    private void ButtonPremiosJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPremiosJuegoActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del juego:"));
            JOptionPane.showMessageDialog(this, casino.getArcade().buscarJuego(id).listarPremios());
        } catch(NumberFormatException | NullPointerException ex){  
        }
    }//GEN-LAST:event_ButtonPremiosJuegoActionPerformed

    private void ButtonEnviarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarComentarioActionPerformed
        // TODO add your handling code here:
        new FormComentario(usuario.getCedula(), casino).setVisible(true);
    }//GEN-LAST:event_ButtonEnviarComentarioActionPerformed

    private void ButtonComentaiosJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonComentaiosJuegoActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del juego:"));
            JOptionPane.showMessageDialog(this, casino.listarComentariosJuego(id));
        } catch(NumberFormatException ex){  
        }
    }//GEN-LAST:event_ButtonComentaiosJuegoActionPerformed

    private void ButtonListarComentariosEnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarComentariosEnviadosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, casino.listarComentariosUsuario(usuario.getCedula()));
    }//GEN-LAST:event_ButtonListarComentariosEnviadosActionPerformed

    private void ButtonRuletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRuletaActionPerformed
        // TODO add your handling code here:
        new RuletaPanel("Ruleta", "",usuario,casino).setVisible(true);
    }//GEN-LAST:event_ButtonRuletaActionPerformed

    private void ButtonTragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTragaActionPerformed
        // TODO add your handling code here:
        new DinoBettingGame("DinoBetting", "",usuario,casino).setVisible(true);
    }//GEN-LAST:event_ButtonTragaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ButtonAggMetodo;
    private javax.swing.JMenuItem ButtonAgregarPremioJuego;
    private javax.swing.JMenuItem ButtonBorrarJuego;
    private javax.swing.JMenuItem ButtonBorrarUsuario;
    private javax.swing.JMenuItem ButtonComentaiosJuego;
    private javax.swing.JButton ButtonDino;
    private javax.swing.JMenuItem ButtonEditarJuego;
    private javax.swing.JMenuItem ButtonEditarPerfil;
    private javax.swing.JMenuItem ButtonEditarUsuario;
    private javax.swing.JMenuItem ButtonEliminarPremioJuego;
    private javax.swing.JMenuItem ButtonEnviarComentario;
    private javax.swing.JMenuItem ButtonListarComentariosEnviados;
    private javax.swing.JMenuItem ButtonListarJuegos;
    private javax.swing.JMenuItem ButtonListarUsuarios;
    private javax.swing.JMenuItem ButtonPremiosJuego;
    private javax.swing.JMenuItem ButtonQuiMetodo;
    private javax.swing.JButton ButtonRuleta;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JButton ButtonTraga;
    private javax.swing.JMenuItem ButtonTransacción;
    private javax.swing.JMenuItem ButtonVerCartera;
    private javax.swing.JMenuItem ButtonVerMetodos;
    private javax.swing.JMenuItem ButtonVerTransacciones;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuCartera;
    private javax.swing.JMenu MenuGestionar;
    private javax.swing.JMenu MenuJuegos;
    private javax.swing.JMenu MenuPerfil;
    private javax.swing.JMenu MenuSoporte;
    private javax.swing.JMenu MenuUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
